spring:
  application:
    name: xfsw-web-fe-entry

server:
  port: 8201

eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8001/eureka/
      
security:   
  user:  
    name: xfsw #eureka 用户名  
    password: xfsw-eureka #eureka 密码  