spring:
  profiles: eureka3
  application:  
    name: xfsw-eureka-server
security:   
  basic:  
    enabled: true #eureka用户是否认证  
  user:  
    name: xfsw #eureka 用户名  
    password: xfsw-eureka #eureka 密码  
server:
  port: 8003     #指定服务端口
eureka:
  instance:
    hostname: eureka-tertiary 
  client:
    registerWithEureka: true  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: true  #从eureka server获取注册信息
    serviceUrl:
      defaultZone: http://eureka-primary:8001/eureka/,http://eureka-secondary:8002/eureka/
