#关于配置文件，后期整理为spring cloud config配置，分环境
server:
  port: 8050

spring:
  application:
    name: datadeck-demo
  hateoas:
    use-hal-as-default-json-media-type: true
  http:
    converters:
      preferred-json-mapper: jackson
  aop:
    auto: true
dd: 
  jdbc: 
    host: localhost
    port: 3306
    database: datadeck
    username: root
    password: 123456
